name: Continuous Integration
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.1
        with:
          linter: pylint

  discord:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Discord Webhook
      uses: Sniddl/discord-commits@v1.6 
      with:
        webhook_url: https://discordapp.com/api/webhooks/1286013310742827149/gEXik3qXzB6KErEOQ7DB6uh6jPR6Kn7P1xwRDMl1Lc-TlHbeh0oS4B7m3Uf0oH9WJN54
        template: "avatar-with-link"
        include-extras: true
